version: "3.3"  # optional since v1.27.0
services:
  odoo:
    image: odoo
    depends_on: 
      - database
    enviroment:
      - HOST=database
      - USER=admin
      - PASSWORD=admin
    volumes:
      - ./odoo/web:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata