version: "3.3"  # optional since v1.27.0
services:
  odoo:
    image: odoo
    depends_on: 
      - database
    ports:
      - "8069:8069"
    environment:
      - HOST=database
      - USER=admin
      - PASSWORD=admin
    volumes:
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata